dist: trusty # only Ubuntu Trusty allows usage of Java 8 in Travis CI
language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "topera-github"
    token:
      secure: "7b6e7ac4ac4aabe7feb6fe67217f0b11e352e99c"
    branches:
      - dev
      - master