dist: trusty # only Ubuntu Trusty allows usage of Java 8 in Travis CI
language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
addons:
  sonarcloud:
    organization: "topera-github"
    #token:
      #secure: "token stored in travis-ci -> repo -> settings -> Environment variables -> SONAR_TOKEN = xxxxx"
    branches:
      - dev # dev is here because by default analyses only master branch
      - master

